#define ANSI_COLOR_BLACK   "<span class= \"black\">"
#define ANSI_COLOR_RED     "<span class= \"red\">"
#define ANSI_COLOR_GREEN   "<span class= \"green\">"
#define ANSI_COLOR_YELLOW  "<span class= \"yellow\">"
#define ANSI_COLOR_BLUE    "<span class= \"blue\">"
#define ANSI_COLOR_MAGENTA "<span class= \"magenta\">"
#define ANSI_COLOR_CYAN    "<span class= \"cyan\">"
#define ANSI_COLOR_WHITE   "<span class= \"white\">"

#define ANSI_COLOR_BBLACK   "<span class= \"bblack\">"
#define ANSI_COLOR_BRED     "<span class= \"bred\">"
#define ANSI_COLOR_BGREEN   "<span class= \"bgreen\">"
#define ANSI_COLOR_BYELLOW  "<span class= \"byellow\">"
#define ANSI_COLOR_BBLUE    "<span class= \"bblue\">"
#define ANSI_COLOR_BMAGENTA "<span class= \"bmagenta\">"
#define ANSI_COLOR_BCYAN    "<span class= \"bcyan\">"
#define ANSI_COLOR_BWHITE   "<span class= \"bwhite\">"

#define ANSI_COLOR_RESET   "</span>"
